"""Build the weight calibration notebook.

Assembles analysis/weight_calibration.ipynb from the saved calibration
artefacts. Run after calibration_results.json and figures/ are generated.
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

REPO_ROOT = Path(__file__).resolve().parent.parent
NOTEBOOK_PATH = REPO_ROOT / "analysis" / "weight_calibration.ipynb"


def md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text)


def code(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(source)


def build() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb.cells = []

    nb.cells.append(md(
        "# Weight calibration\n"
        "\n"
        "Measurement Maturity Framework: fitting deduction weights to human judgment.\n"
        "\n"
        "The Bayesian robustness notebook showed MMF's rule-based weights are stable under "
        "uncertainty: within a plausible range they barely change pack rankings. That is a "
        "necessary condition for trusting the framework. This notebook tests a sufficient one: "
        "are the weights close to what an analyst would choose if they ranked packs by "
        "decision-readiness and weights were fitted to match?\n"
        "\n"
        "Mostly yes, with three revisions. MMF agrees with a consensus human ranking at ρ = "
        "0.95. A ridge-regression fit raises that to ρ = 0.99, and the fitted weights point to "
        "three real corrections: `missing_sql` doubled, `missing_owner` up 50%, `tier_v0` "
        "halved.\n"
        "\n"
        "## Scope and caveats\n"
        "\n"
        "This is a calibration attempt, not a definitive calibration. A real one would use at "
        "least three independent human raters, ideally from different backgrounds. This one has:\n"
        "\n"
        "- One human rater (me), who ranked the 27 synthetic packs twice, a few minutes apart, "
        "with a different model of gap severity each time.\n"
        "- One LLM rater (Claude), which ranked the same 27 packs with documented "
        "first-principles weights chosen to differ from MMF's. Its ranking was recorded before I "
        "finalised mine.\n"
        "- A consensus from the average of the three rankings.\n"
        "\n"
        "The limits of this setup:\n"
        "\n"
        "1. I'm not independent of the framework. I built MMF, and my sense of "
        "decision-readiness comes from the same reasoning that produced its weights.\n"
        "2. The LLM rater thinks about metric quality in much the same way I do, which pushes "
        "our rankings together whether or not either is right.\n"
        "3. The raters weren't fully blind to each other. The LLM's ranking was visible in the "
        "session before I finalised mine; the setup couldn't avoid it.\n"
        "4. n = 27. A ridge regression with 7 features on 27 packs can overfit. Read the fitted "
        "weights as a direction for revisions, not a replacement configuration.\n"
        "5. The packs are synthetic, generated by `analysis/generate_synthetic_packs.py`. Real "
        "packs may behave differently.\n"
        "\n"
        "What it supports: a defensible directional case that `missing_sql` is underweighted, "
        "`tier_v0` is overweighted, and the overall weight structure is sensible.\n"
        "\n"
        "What it doesn't support: shipping a replacement weight configuration without more "
        "validation."
    ))

    nb.cells.append(code(
        "# Setup\n"
        "import json\n"
        "import sys\n"
        "from pathlib import Path\n"
        "\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "from scipy.stats import kendalltau, spearmanr\n"
        "\n"
        "REPO_ROOT = Path.cwd().parent if Path.cwd().name == 'analysis' else Path.cwd()\n"
        "sys.path.insert(0, str(REPO_ROOT))\n"
        "\n"
        "CALIB = REPO_ROOT / 'analysis' / 'calibration'\n"
        "FIG = CALIB / 'figures'\n"
        "print(f'Calibration artefacts: {CALIB}')"
    ))

    # ---------------------------------------------------------------------
    # Test-retest
    # ---------------------------------------------------------------------

    nb.cells.append(md(
        "## Test-retest reliability of the human rater\n"
        "\n"
        "First, a question calibration studies rarely ask, because most use one pass: how stable "
        "is the human ranking? If the same person ranks the same 27 packs twice, how well do the "
        "rankings agree?\n"
        "\n"
        "The rater did exactly that, and between attempts deliberately changed their own model "
        "of gap severity (V0 went from critical to medium; description went the other way). Even "
        "so, the two attempts agree at:\n"
        "\n"
        "- Spearman ρ = 0.974\n"
        "- Kendall τ = 0.892\n"
        "\n"
        "This matters for everything below. With low test-retest reliability (say τ < 0.75), a "
        "calibration on the human ranking would be built on noise. At τ = 0.89 the rater is "
        "stable enough for the calibration to mean something, even though their reasoning about "
        "why some packs scored as they did changed between attempts."
    ))

    nb.cells.append(code(
        "from IPython.display import Image, display\n"
        "display(Image(str(FIG / 'test_retest.png')))\n"
        "\n"
        "v1 = pd.read_csv(CALIB / '_user_ranking.csv', decimal=',')[['pack_id', 'your_rank']].rename(columns={'your_rank': 'v1'})\n"
        "v2 = pd.read_csv(CALIB / '_user_ranking_v2.csv').rename(columns={'user_rank_v2': 'v2'})\n"
        "merged = v1.merge(v2, on='pack_id')\n"
        "rho, _ = spearmanr(merged['v1'], merged['v2'])\n"
        "tau, _ = kendalltau(merged['v1'], merged['v2'])\n"
        "print(f'Test-retest: Spearman={rho:.4f}, Kendall={tau:.4f}')\n"
        "\n"
        "merged['shift'] = (merged['v1'] - merged['v2']).abs()\n"
        "print('\\nLargest shifts between attempts:')\n"
        "print(merged.nlargest(5, 'shift')[['pack_id', 'v1', 'v2', 'shift']].to_string(index=False))"
    ))

    nb.cells.append(md(
        "The five biggest re-ranks are interesting. `prod_ready_02` moved from rank 3 to 8 "
        "because missing descriptions mattered more in the second model. "
        "`edge_all_v0_but_documented` moved from 10 to 5 because V0 dropped from critical to "
        "medium. These are principled reassessments, not noise, and the high overall agreement "
        "shows the ordering held for most packs.\n"
        "\n"
        "The average of the two attempts is the human consensus used from here on."
    ))

    # ---------------------------------------------------------------------
    # Three-way ranking comparison
    # ---------------------------------------------------------------------

    nb.cells.append(md(
        "## Three-way ranking agreement\n"
        "\n"
        "With the human consensus (mean of two attempts), the LLM ranking and MMF's rule-based "
        "scores, we can measure agreement between each pair."
    ))

    nb.cells.append(code(
        "df = pd.read_csv(CALIB / 'all_rankings_merged.csv')\n"
        "\n"
        "pairs = [\n"
        "    ('user_consensus', 'claude_rank', 'User vs Claude'),\n"
        "    ('user_consensus', 'mmf_rank', 'User vs MMF'),\n"
        "    ('claude_rank', 'mmf_rank', 'Claude vs MMF'),\n"
        "]\n"
        "print(f'{\"pair\":<24} {\"Spearman\":>10} {\"Kendall\":>10}')\n"
        "print()\n"
        "for a, b, label in pairs:\n"
        "    rho, _ = spearmanr(df[a], df[b])\n"
        "    tau, _ = kendalltau(df[a], df[b])\n"
        "    print(f'{label:<24} {rho:>10.4f} {tau:>10.4f}')\n"
        "\n"
        "display(Image(str(FIG / 'three_way_ranks.png')))"
    ))

    nb.cells.append(md(
        "Three things stand out:\n"
        "\n"
        "1. The human and Claude agree more with each other (τ=0.92) than either does with MMF "
        "(τ≈0.82 to 0.84). The two human-like raters share some intuition MMF's weights miss.\n"
        "2. MMF still does well. A Spearman ρ of 0.94 to 0.95 against human judgment is a good "
        "baseline for a rule-based scorer with judgment-set weights.\n"
        "3. The disagreements are concentrated. Most rankings track closely, and a few packs "
        "account for most of the difference. Those packs show what to fix."
    ))

    # ---------------------------------------------------------------------
    # Fitted weights
    # ---------------------------------------------------------------------

    nb.cells.append(md(
        "## Fitted weights\n"
        "\n"
        "To find the weights that best explain the consensus ranking, a ridge regression "
        "(positive=True, so weights can't go negative) uses gap counts per metric as features "
        "and the mean rank as the target. Ridge regularisation (α=1.0) damps the extreme "
        "coefficients small samples tend to produce.\n"
        "\n"
        "The fitted weights, scaled so the largest equals MMF's largest (10):"
    ))

    nb.cells.append(code(
        "display(Image(str(FIG / 'fitted_weights.png')))\n"
        "\n"
        "results = json.loads((CALIB / 'calibration_results.json').read_text())\n"
        "mmf = results['mmf_baseline_weights']\n"
        "fit = results['fitted_weights']\n"
        "comparison = pd.DataFrame({\n"
        "    'gap': list(mmf.keys()),\n"
        "    'mmf': list(mmf.values()),\n"
        "    'fitted': [fit[k] for k in mmf],\n"
        "})\n"
        "comparison['delta'] = comparison['fitted'] - comparison['mmf']\n"
        "print(comparison.to_string(index=False))"
    ))

    nb.cells.append(md(
        "### What the fitted weights say\n"
        "\n"
        "| Weight | Change | Why |\n"
        "|---|---|---|\n"
        "| `missing_sql` | Doubles (5 → 10) | Both raters penalised missing SQL more than MMF. "
        "Without SQL the metric can't be reproduced or audited, and they treated that as about "
        "as bad as any single gap. |\n"
        "| `missing_owner` | Up 50% (5 → 7.5) | With no accountable team, nobody answers when "
        "the metric drifts. Both raters weighted it above MMF's default. |\n"
        "| `tier_v0` | Halved (10 → 5.4) | The biggest correction. MMF treats V0 as the worst "
        "single gap; the calibration says mid-weight. V0 signals a temporary proxy, and when the "
        "proxy is otherwise well documented (SQL, owner, tests) the tag shouldn't dominate the "
        "score. |\n"
        "| `missing_grain` | Doubles (2 → 3.9) | Knowing what one row represents matters "
        "structurally. The human rater called it medium severity in the second ranking. |\n"
        "| `missing_description`, `missing_tests`, `missing_unit` | About the same or slightly "
        "lower | MMF's weights are broadly right. |\n"
        "\n"
        "### How much does it help?\n"
        "\n"
        "With MMF's default weights, the pack ranking agrees with the human consensus at "
        "Spearman ρ = 0.953. With the fitted weights, ρ = 0.993: about 0.04 more correlation, "
        "roughly half as many rank inversions.\n"
        "\n"
        "Read that carefully. The fitted weights will always agree with the consensus better "
        "than MMF's, because the fit optimises exactly that agreement on exactly this data. The "
        "real question is whether the changes hold on a bigger or more varied corpus, and 27 "
        "packs can't answer it."
    ))

    # ---------------------------------------------------------------------
    # Recommendations
    # ---------------------------------------------------------------------

    nb.cells.append(md(
        "## Recommendations for MMF, and what shipped\n"
        "\n"
        "Three weight changes survive the caveats and are worth recording as directional "
        "findings. Each has its actual status (shipped, held, or held with a structural "
        "alternative) so the notebook doesn't overstate its effect on the live framework.\n"
        "\n"
        "### Finding 1: `missing_sql` is underweighted\n"
        "\n"
        "Recommendation: raise `missing_sql` from -5 to -8 or -10. The human rater (in both "
        "attempts) and the LLM rater both placed missing SQL as the worst single gap. It also "
        "matches an independent design critique in "
        "[SCORING_METHODOLOGY.md](../SCORING_METHODOLOGY.md) that `missing_sql` is too coarse "
        "when the implementation can't be reviewed at all.\n"
        "\n"
        "Status: structural change shipped, magnitude change held. The gap is now split into "
        "`missing_sql_temporary` (-3) and `missing_sql_structural` (-12), chosen by an optional "
        "`implementation_type` field on each metric. That addresses the structural critique "
        "without relying on a small-sample fit. Raising the default `missing_sql` from -5 to -8 "
        "is deliberately not shipped.\n"
        "\n"
        "### Finding 2: `tier_v0` is overweighted\n"
        "\n"
        "Recommendation: lower `tier_v0` from -10 to -5 or -6. A V0 tag is useful information, "
        "not a severe defect. Over-penalising it makes V0 tagging painful and discourages the "
        "honest declaration of instability the framework wants.\n"
        "\n"
        "Status: held. Shipping it would mean rerunning the robustness analysis and updating 27 "
        "synthetic pack scores, the case study scores and the regression tests, all for a change "
        "backed by two raters on synthetic data. Not a good trade when the notebook itself warns "
        "against shipping without more rigour.\n"
        "\n"
        "### Finding 3: `missing_owner` is slightly underweighted\n"
        "\n"
        "Recommendation: raise `missing_owner` from -5 to -7. Ownership gaps are process "
        "failures that compound over time, and the fit supports treating them as a little more "
        "severe than MMF does.\n"
        "\n"
        "Status: held, for the same reason as Finding 2.\n"
        "\n"
        "The other fitted changes (grain up, tests slightly down) are within the noise of a "
        "single-rater, small-sample calibration and aren't defensible recommendations.\n"
        "\n"
        "### What this calibration can't tell us\n"
        "\n"
        "- Whether the weights generalise beyond the 27 synthetic packs.\n"
        "- Whether a more varied rater pool would produce different weights.\n"
        "- Whether there are interactions (for example \"V0 with no owner\" being worse than the "
        "sum of its parts) that a linear model can't capture.\n"
        "- Whether weights should vary by metric tier (V0, V1, V2+).\n"
        "\n"
        "Each needs more raters, more packs or a richer model."
    ))

    # ---------------------------------------------------------------------
    # Reproducibility
    # ---------------------------------------------------------------------

    nb.cells.append(md(
        "## Reproducibility\n"
        "\n"
        "Everything is saved in `analysis/calibration/`:\n"
        "\n"
        "| File | Contents |\n"
        "|---|---|\n"
        "| `_user_ranking.csv` | Human rater, first attempt |\n"
        "| `_user_ranking_v2.csv` | Human rater, second attempt |\n"
        "| `_claude_ranking.csv` | LLM rater's ranking |\n"
        "| `_mmf_reference_scores.csv` | MMF scores (not shown to raters) |\n"
        "| `all_rankings_merged.csv` | All rankings joined per pack |\n"
        "| `calibration_results.json` | Fitted weights and summary statistics |\n"
        "| `figures/` | PNG outputs used here |\n"
        "\n"
        "This notebook is generated by `analysis/build_calibration_notebook.py` and the figures "
        "by `analysis/build_calibration_figures.py`. Both read the CSVs above and are "
        "deterministic given those inputs."
    ))

    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10+"},
    }
    return nb


def main() -> None:
    nb = build()
    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    with NOTEBOOK_PATH.open("w") as f:
        nbf.write(nb, f)
    print(f"Wrote {NOTEBOOK_PATH}")


if __name__ == "__main__":
    main()
